version: '3.8'
services:
  apache:
    image: php:8.2-apache
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=ruslan
      - MYSQL_PASSWORD=0000

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=0000
